#!/usr/bin/env python

import os
import sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'server.settings'
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'],'RemoteAlarm' ,  'server','remoteAlarmSrc'))
virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
#os.environ['OPENSHIFT_APP_NAME']=''  # Or path to database file if using sqlite3.
os.environ['OPENSHIFT_DB_USERNAME']='adminTm7ACQY',                      # Not used with sqlite3.
os.environ['OPENSHIFT_DB_PASSWORD']='Z8EdZpIRqW-Y',                  # Not used with sqlite3.
os.environ['OPENSHIFT_DB_HOST']='twt',                      # Set to empty string for localhost. Not used with sqlite3.
#os.environ['OPENSHIFT_DB_PORT']=''   
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
